### ISSUE TITLE
Two more minor design issues

### ISSUE THREAD

**Issue by rkzack** [ournews/extensions#36]
@webcolor-in please take a look at these two issues on:

`https://thehill.com/homenews/sunday-talk-shows/466638-white-house-officials-work-to-tamp-down-anger-after-a-tumultuous`

![2019-10-20_1915](https://user-images.githubusercontent.com/35204816/67168077-5c2e4880-f36e-11e9-9d67-ab2646187812.png)

**Comment by webcolor-in** [comment]
Fixed

**Comment by rkzack** [comment]
The notification circle is fixed, but the Submit Article button is still the wrong color on any article you're adding from thehill.com.  Here's another: `https://thehill.com/homenews/administration/466538-diplomats-describe-all-time-low-in-morale-at-state-under-trump`

**Comment by webcolor-in** [comment]
I couldn't reproduce this issue so couldn't verify.. however I have added additional css to put right color for this button. You can verify and let me know if that fixed, code pushed.

**Comment by rkzack** [comment]
I'm afraid it's still not working, see below. You can reproduce on this link:

`https://thehill.com/homenews/administration/466538-diplomats-describe-all-time-low-in-morale-at-state-under-trump`

![Screen Shot 2019-10-21 at 9 44 24 AM](https://user-images.githubusercontent.com/35204816/67210625-63456d00-f3e7-11e9-94d3-3e875dbe5dc7.png)

**Comment by webcolor-in** [comment]
I think they inject different style for different laptops so its not showing up for me. But I am sure there exist issue checking the screenshot you sent.

![Annotation 2019-10-21 193619](https://user-images.githubusercontent.com/55145799/67212483-150d8980-f43a-11e9-9293-51f28e5604ab.png)

**Comment by webcolor-in** [comment]
Let me know if this is still happening

**Comment by rkzack** [comment]
Yes, I just tried this again and it's still happening with the latest version.

**Comment by webcolor-in** [comment]
There was conflict but .button classname so I updated this such that to better classname. Its working now in mac version of site as well.

**Comment by rkzack** [comment]
This is also fixed, thank you. Closing issue.
